stats: Fix a compile warning in meminfo processing
When reading /proc/meminfo for stats, the buffer was missing space for
the final NUL byte. Caught via compile warning:

> ```
> src/util.c:648:56: error: 'sscanf' may overflow; destination buffer
> in argument 5 has size 4, but the corresponding specifier may require
> size 5 [-Werror,-Wfortify-source]
>
>   648 |         if (sscanf(line, "%127s %ld %4s", key, &value, unit) != 3)
>       |                                                        ^
> 1 error generated.
> ```