include_server: Fix binary read for --verify
When opened with rb, there cannot be an encoding given; it's a python3
error:

```
>>> open("/tmp/main.c", "rb", encoding="latin-1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: binary mode doesn't take an encoding argument
```

I believe we aren't at risk of losing dependencies here (they're likely
to be ascii), so this commit removes the binary qualifier.

Signed-off-by: Alex Karle <akarle@mathworks.com>