Add setuptools dependency
When follow the INSTALL file to install distcc, make command will fail by:

ModuleNotFoundError: No module named 'setuptools'
make: *** [Makefile:586: include-server] Error 1

Which should since #493.