fix compilation error without ENABLE_RFC2553
src/access.c:55:22: error: «allones8» defined but not used
[-Werror=unused-const-variable=]
 static const uint8_t allones8 = 0xffU;